export const HOME_PAGE = '/'
export const DETAIL_PAGE = '/detail/$id'
export const SEARCH_PAGE = '/search'
export const VIEW_PAGE = '/view/$bookId/$id'
export const ADMIN_PAGE = '/admin'
export const LOGIN_PAGE = '/login'
